### ISSUE TITLE
In view_mail.cgi $sindex is undefined

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#10]
In:

https://github.com/swelljoe/usermin/blob/master/mailbox/view_mail.cgi#L328

I don't see where $sindex can ever be defined. There's an instance of $sindex in mailbox-lib.pl, but it's pretty deeply nested, and doesn't seem like it was supposed to be global.

**Comment by jcameron** [comment]
Looks like $sindex was being set in another function as a global. I'll check in a fix for that.
