### ISSUE TITLE
menu on left side will not stay opened on iPad

### ISSUE THREAD

**Issue by HonkXL** [webmin/usermin#102]
On iPad (iPad OS 16.5 or 17) the left menu on usermin will not stay opened. It always minimizes itself. This makes Usermin unusable on iPad.
The same problem existed in Webmin I think 1/2 year ago and was fixed there, but in Usermin it is still not working.

Usermin is 1.861

**Comment by iliajie** [comment]
Hello,

This is already known and fixed issue. It will be fixed in upcoming Webmin 2.100 and Usermin 2.000 releases.

**Comment by HonkXL** [comment]
Is there a quick way to fix it now? As far as I know it depends on a css problem!?

**Comment by iliajie** [comment]
The quickest way of fixing it would be to have a look at [webmin.com](https://webmin.com) website and find the way to install nightly Webmin and/or Usermin version, which include all latest patches and fixes.
