### ISSUE TITLE
Question: html tags visible in Usermin filter list?

### ISSUE THREAD

**Issue by ksihota** [webmin/usermin#105]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     CentOS Linux 7.9.2009     |
|  Webmin version      |     2.102      |
|  Usermin version     |     2.002     |
|  Virtualmin version  |     7.7       |
|  Theme version       |     21.05      |
|  Package updates     |     All installed packages are up to date   |

Just updated Usermin and Webmin.

Are these tags supposed to be visible in the filter list?

![image](https://github.com/webmin/usermin/assets/29150649/37d81b63-0f72-4472-b1ed-a98682dbc822)

**Comment by jcameron** [comment]
Sorry, that's a bug in the latest release :-(

We'll fix it in the next version ...
