### ISSUE TITLE
resetting usermin theme to global default causes errors and inability to log in

### ISSUE THREAD

**Issue by fanto666** [webmin/usermin#107]
When I set user theme to "framed theme" and then back to "global usermin default",
this results into failure to login as given user, producing error:

Perl execution failed : Undefined subroutine &main::ui_switch_theme_javascript called at /usr/share/usermin/web-lib-funcs.pl line 1122.

in both web browser and the miniserv.error file.

The first change writes "theme_$USER=gray-theme" to /etc/usermin/config and "preroot_$USER=gray-theme" into /etc/usermin/miniserv.conf, where $USER is the username for which theme was set (if this is not obvious).

the latter change resets both themes to empty strings, which causes the mentioned error.

That error can be currently fixed by manual removing of lines "theme_$USER=" from /etc/usermin/config and "preroot_$USER=" from /etc/usermin/miniserv.conf
AND restarting usermin. 

It would be better if theme was saved in users' home directory at other usermin options.

**Comment by iliajie** [comment]
Alright, thanks for the heads up! We will fix both of these issues!
