### ISSUE TITLE
from: address guessing fails when no To: header 

### ISSUE THREAD

**Issue by fanto666** [webmin/usermin#109]
in "Mail Forwarding and Replies" module,
when user selects "From: address for replies 	Guess based on recipient"
and e-mail comes without the To:/Cc: headers,
sending automatic reply fails with sendmail error:
Feb 27 11:38:09 mail postfix/sendmail[28651]: fatal: usage: sendmail [options]

while it's fair that no reply is sent in this case, I believe the autoreply,pl script should detect this and silently exit.

**Comment by jcameron** [comment]
Good idea, I'll do this in the next release.
