### ISSUE TITLE
In view_mail.cgi $dsntm is defined but never used

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#11]
In:

https://github.com/swelljoe/usermin/blob/master/mailbox/view_mail.cgi#L366

https://github.com/swelljoe/usermin/blob/master/mailbox/view_mail.cgi#L376

$dsntm gets defined, but doesn't get used anywhere that I can see.

**Comment by jcameron** [comment]
Thanks, I've checked in a fix for this.

**Comment by swelljoe** [comment]
In the second instance, should it actually be called with localtime? Looks like make_date doesn't need/want that?
