### ISSUE TITLE
Date field not decoded in Email viewer.

### ISSUE THREAD

**Issue by chris001** [webmin/usermin#111]
![usermin email date text format issue 1](https://github.com/webmin/usermin/assets/259416/095c6dbf-36b7-4f4d-8dfd-ded67e7aa244)

![usermin email date text format issue 2](https://github.com/webmin/usermin/assets/259416/5a8d467b-f34c-4b62-969e-48037a7bf72c)

**Comment by jcameron** [comment]
Can you show me the raw `Date:` header in this email?

**Comment by iliajie** [comment]
Is this latest Webmin?

**Comment by chris001** [comment]
Webmin 2.105.  
Usermin 2.005.
![usermin email date text format issue 3](https://github.com/webmin/usermin/assets/259416/ea63d9e8-97f2-4dca-9977-fb8c23adf6b8)

**Comment by jcameron** [comment]
Looks like there's some double-escaping going on here with the date. Does this still happen if you switch to the older Framed Theme in Usermin?

**Comment by chris001** [comment]
Yes
![usermin email date text format issue 4](https://github.com/webmin/usermin/assets/259416/971873ac-f7e5-4e15-8175-5be952cb1470)

**Comment by iliajie** [comment]
We should just allow `&nbsp;`, perhaps!

**Comment by jcameron** [comment]
@iliajie the problem code is here : https://github.com/webmin/webmin/blob/master/web-lib-funcs.pl#L2263

I see now reason for this though, and it makes assumptions about what escaping the caller will do! I will just remove that conversion to nbsp.

**Comment by iliajie** [comment]
It wasn't added by accident. It may break in modules like Webmin Actions Log.

**Comment by jcameron** [comment]
How would it break anything? Other than perhaps effecting the wrapping ...

**Comment by iliajie** [comment]
Well, this code is there by a reason. There are modules in Webmin that do splitting in a way that expect time value to be `(\S+)` in a table cell, and I wasn't sure how many more modules were there doing the same, so I worked around it.

So, for example, if I locally remove [this](https://github.com/webmin/webmin/blob/master/web-lib-funcs.pl#L2263) code, this is how things break:

<img width="1089" alt="image" src="https://github.com/webmin/usermin/assets/4426533/09380945-21e5-47de-8e1a-91286a56bf25">

It breaks in much worse way in Authentic.

**Comment by jcameron** [comment]
Oh I see, that's really a bug in the Webmin Actions Log module - it shouldn't be assuming anything about the date format!

I have fixed that here : https://github.com/webmin/webmin/commit/3a275d1d5b696f924be1f11f1b45c6acb4308472

Are there any other modules that split up the date like this?

**Comment by iliajie** [comment]
> Are there any other modules that split up the date like this?

This is the reason why I had to implement the work-around in the first place, as I simply don't know if there are any other modules doing the same or or not.

**Comment by jcameron** [comment]
I looked through the code, and fixed one more case here : https://github.com/webmin/webmin/commit/83c93d8bdca38cd72034f014eff83fa6ef1fccb1

Basically, callers shouldn't assume that `make_date` has a particular format, and calling split on it is a bug. We should fix all those bugs, instead of trying to solve it inside the `make_date` function.

**Comment by iliajie** [comment]
> We should fix all those bugs, instead of trying to solve it inside the `make_date` function.

Yes, agreed! It is always best ideally speaking! I will apply your code and keep looking around in case I find something that's broken. I will also remove mentioned earlier code from `make_date` sub.

Thanks!

**Comment by iliajie** [comment]
I have removed that line with a work-around.

**Comment by jcameron** [comment]
Thanks Ilia!

**Comment by iliajie** [comment]
Welcome!
