### ISSUE TITLE
List of mails in spam folder messed up sometimes

### ISSUE THREAD

**Issue by HonkXL** [webmin/usermin#112]
Sometimes I receive a mail that messes up the list of the mails in Spam folder.
See screenshot.

![spam-folder](https://github.com/webmin/usermin/assets/16715040/7d618b06-0f61-4e02-910c-a1dfdcb10801)

And here is the mail that broke the list. When deleting this mail, everything is fine. I modified the servername and mail address for privacy reasons.

[spammail.txt](https://github.com/user-attachments/files/15839464/spammail.txt)

**Comment by iliajie** [comment]
Oh, wow! That's crazy! I can reproduce that as well. I will take a closer look shortly and update this ticket with progress.

**Comment by iliajie** [comment]
Thanks for the heads up! We will fix it in the next Usermin release.
