### ISSUE TITLE
Add column headers

### ISSUE THREAD

**Issue by shoulders** [webmin/usermin#114]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      107  package updates are available   |

### The request

Is it possible to add column headers. This view just seems naked.

![image](https://github.com/user-attachments/assets/334c1558-1abb-495b-854e-f27a9507c971)

### Additional

I would put the name of the current folder at the top, makes the page less naked.

![image](https://github.com/user-attachments/assets/30f74cff-8cff-4894-bc0e-8094a70cff90)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

I doubt it's going to be useful in any way. The currently selected mail folder is associated with the selected item in the navigation menu. Google Mail seems to do the same. Though Proton Mail shows it, but only when nothing is selected.

Implementing it nicely like in Proton will be time-consuming. I don't think it's worth the time spent.

**Comment by iliajie** [comment]
> And the columns headers? Is this worth looking at or was that included in the response above 😄

I don't think we need to display headers either. It has no practical application when listing mail.

**Comment by jcameron** [comment]
We have column headers in the Webmin/Usermin theme though, right?

**Comment by iliajie** [comment]
> We have column headers in the Webmin/Usermin theme though, right?

We do have it in Webmin, but the mail listing is different there. Contemporary mail clients like Gmail don't have those obvious column headers.
