### ISSUE TITLE
Usermin / Change User Details / Real name utf-8 backslash escaped

### ISSUE THREAD

**Issue by fanto666** [webmin/usermin#115]
When we set users' Real name in webmin, it shows in passwd correctly
but when they do the same in usermin's Change User Details, the diacritics characters get backslash before every utf-8 byte:

testtest:x:1000:1000:test \�\�e\�\�\�\�:/home/testtest:/bin/bash

00000000  74 65 73 74 74 65 73 74  3a 78 3a 31 30 30 30 3a  |testtest:x:1000:|
00000010  31 30 30 30 3a 74 65 73  74 20 5c c5 5c a5 65 5c  |1000:test \.\.e\|
00000020  c5 5c a1 5c c5 5c a5 3a  2f 68 6f 6d 65 2f 74 65  |.\.\.\.:/home/te|
00000030  73 74 74 65 73 74 3a 2f  62 69 6e 2f 62 61 73 68  |sttest:/bin/bash|
00000040  0a                                                |.|
00000041

when I remove backslashed, Real name shows correctly:

testtest:x:1000:1000:test ťešť:/home/testtest:/bin/bash

00000000  74 65 73 74 74 65 73 74  3a 78 3a 31 30 30 30 3a  |testtest:x:1000:|
00000010  31 30 30 30 3a 74 65 73  74 20 c5 a5 65 c5 a1 c5  |1000:test ..e...|
00000020  a5 3a 2f 68 6f 6d 65 2f  74 65 73 74 74 65 73 74  |.:/home/testtest|
00000030  3a 2f 62 69 6e 2f 62 61  73 68 0a                 |:/bin/bash.|
0000003b

Please unescape the backslashes when saving Real name.

**Comment by iliajie** [comment]
Hello,

> but when they do the same in usermin's Change User Details, the diacritics characters get backslash before every utf-8 byte

😄 Interesting! What exactly are you submitting on the form? Could you provide an example? You can change the actual name, but keep some of the characters that were used.

**Comment by fanto666** [comment]
I did not change anything, I entered the same text that was already there
- as is then seen in fullname 
"ťešť" - just  a "test"
each utf-8 character in this case is sequence of 2 bytes between 0x80-0xff, those are escaped with backslashes when changed via usermin
- changing via webmin is okay.

**Comment by iliajie** [comment]
Thanks for clearing this up! The fix is here https://github.com/webmin/usermin/commit/e5b18ab1bf4b25cfbdd3429ec06658d92b7ddc38.
