### ISSUE TITLE
In mailbox-lib.pl $dn is undefined in connect_qmail_ldap

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#12]
In this line: 

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1887

$dn is undefined. I see $dn being defined as $userconfig{'drafts_name'} in line 504, but that doesn't seem to make sense in this context, so I didn't just set it to that. I'm not sure what it's supposed to be here.

**Comment by jcameron** [comment]
I've checked in a fix for this.
