### ISSUE TITLE
Inconsistent buttons/menus naming for whitelist/allow and blacklist/deny sender actions in webmail UI

### ISSUE THREAD

**Issue by nekohayo** [webmin/usermin#120]
This is a small UX detail, but there is a semantic/linguistic inconsistency in the way these actions are named.

Within the messages list view's extra actions toolbar submenu, when a message is selected, they are named "Mark as blacklisted" and "Mark as whitelisted" 

![image](https://github.com/user-attachments/assets/79d3375c-718b-46fa-a6db-1c059b74a4f8)

...but that is a bit ambiguous because it's about the _sender_ rather than the _message,_ so it might be better to name them "Block sender" and "Allow sender" (or "Always allow this sender"). Avoiding the terms "blacklist" and "whitelist" might also be desirable for cultural reasons.

For comparison, within an individual message's view's toolbar, they are named "Deny sender" and "Allow sender" (but I think that "Block" may be clearer to laypeople than "Deny"):

![image](https://github.com/user-attachments/assets/1b240ddf-35e8-4e68-bf42-237350259d8d)

--

Observed on my personal usermin 2.102 webmail interface (authentic theme 21.20.7) from your Debian repositories

**Comment by iliajie** [comment]
Thanks! That’s a great suggestion! We’ll get it fixed!
