### ISSUE TITLE
Paragraph spacing not rendered in WYSIWYG preview while composing emails in the webmail interface

### ISSUE THREAD

**Issue by nekohayo** [webmin/usermin#121]
In usermin 2.102's webmail interface, when you are composing a rich (i.e. HTML) email, from the "+ New message" sidebar button that creates an overlay email composer, paragraphs spacing is not properly rendered.

That is, if you type some text, then hit `Enter` to create a new paragraph (or start a list of bullet points), type something, it will show up like this in the composer, as if it was just a linebreak but not a paragraph break:

```
This is the first paragraph, let's hit the `Enter` key to create a new paragraph...
Blah blah blah this is a new paragrah
* This is a bulleted list paragraph
* Yay  
And this is another paragraph
```

So in practice, as a user, you think those are just line breaks, so you hit `Enter` twice so that you can actually see paragraphs looking like this in the composer:

```
This is the first paragraph, let's hit the `Enter` key _twice_ to create a new paragraph...

Blah blah blah this is a new paragrah

* This is a bulleted list paragraph
* Yay

And this is another paragraph
```

...but the problem is that the composer's WYSIWYG doesn't match reality. When you send the email and go to the "Sent" folder, whether in the webmail client or any other mail client, you will see that the double line returns created huge empty spaces between paragraphs, a bit like this:

```
This is the first paragraph, let's hit the `Enter` key _twice_ to create a new paragraph...
  
  
Blah blah blah this is a new paragrah  
  
  
* This is a bulleted list paragraph
* Yay
  
  
And this is another paragraph
```

As seen here with this real-world example:

![image](https://github.com/user-attachments/assets/4ee2e488-8974-4c2d-9df5-07fada6f1778)

I think the solution would be for the composer to actually render paragraph spacings (like the actual output that gets sent) so that users don't feel compelled to press Enter twice.

**Comment by iliajie** [comment]
Yeah, I see this too. It happens because an empty paragraph is added as `<p><br></p>` rather than `<p></p>`. This could probably be fixed, but I don’t think it would be a trivial change.

**Comment by iliajie** [comment]
This will be fixed on the next Webmin release.
