### ISSUE TITLE
Inconsistent font family usage between mail composer and message view's contents in webmail UI

### ISSUE THREAD

**Issue by nekohayo** [webmin/usermin#122]
This is a minor UX issue I've noticed with usermin 2.102's webmail interface, with the default "authentic theme" 21.20.7 and using Firefox 132 or Epiphany 47 on Fedora 41: when you compose and send an email from the web interface, then go to the Sents folder to look at it, you will see that the email's body text will used serifed fonts, unlike what was shown in the composer, and unlike all the rest of the interface, so it looks/feels out of place (also, the font size ends up being completely different):

![image](https://github.com/user-attachments/assets/1b5a0e88-b9b1-4c0c-a353-d83a193d8d7b)

I understand that this is probably because the composer does not set a particular font family in the emails it sends out (and indeed some other email clients do not define the outgoing font, either) so it probably fallbacks to "whatever the web browser suggest" which happens to be "Serif", but that creates an inconsistent user experience within the webmail interface. Most mail clients will render undefined fonts with Sans Serif to match the rest of the interface, or they will use a document font that matches what the operating system has set. Or at least, if they are going to use serifed fonts, they would specifically use some elegant ones (such as [Libertinus](https://github.com/alerque/libertinus)) instead of "what the browsers defaulted to in 1998".

My suggestion would be to dynamically render the HTML emails' fallback font using the same font as the rest of the webmail UI.

**Comment by iliajie** [comment]
> I understand that this is probably because the composer does not set a particular font family in the emails it sends out

That’s correct. We don’t set it explicitly—when HTML mail is composed, we simply let the browser use whatever the OS default.

> but that creates an inconsistent user experience within the webmail interface.

Consistency can be a bit questionable for HTML messages.

> or they will use a document font that matches what the operating system has set.

Yes, that’s exactly how it should work.

> My suggestion would be to dynamically render the HTML emails' fallback font using the same font as the rest of the webmail UI.

Well, this should definitely be doable.

**Comment by iliajie** [comment]
Alright, the next Webmin release will display HTML and text emails more consistently, aligning them with the rest of the UI.
