### ISSUE TITLE
Usermin config produces broken HTML

### ISSUE THREAD

**Issue by qooob** [webmin/usermin#16]
Jamie, `uconfig.cgi` always puts `Return to index` button inside of the container.

It should be on the outside. Probably something is missing.

Example:
![screenshot from 2017-04-24 14-46-11](https://cloud.githubusercontent.com/assets/4426533/25335779/259b869a-28fd-11e7-9ea2-01ce321576a8.png)
![screenshot from 2017-04-24 14-44-04](https://cloud.githubusercontent.com/assets/4426533/25335780/259e8f3e-28fd-11e7-950b-7e88b60943cc.png)

**Comment by jcameron** [comment]
Thanks - I've just checked in a fix for this here : https://github.com/webmin/usermin/commit/6e539d91e552a94e23a1a4fb42d62b1287711b00
