### ISSUE TITLE
repo link Webmin broken?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/usermin#21]
Hi, after an update of usermin I stay with a broken link  from repo.

Webmin ->  ../webadmin/Webmin

wich did not exist.
lokking on the files in it after RPM install it sould be

Webmin ->  ../webadmin/WebminUI

**Comment by jcameron** [comment]
Can  you explain the error message that you're getting? I don't undertstand the problem.

**Comment by gnadelwartz** [comment]
no error message, I noticed simply in usermin was a stale link `Webmin` pointing pointing to `../webadmin/Webmin` but in in webadmin/webmin and in webmin repo is is no directory `Webmin` onyl `WebminUI` and `Webmin-API-1.0`

![grafik](https://cloud.githubusercontent.com/assets/4593242/26253893/1dad2418-3cb5-11e7-8d45-21492f08849f.png)
 
![grafik](https://cloud.githubusercontent.com/assets/4593242/26253949/4be63482-3cb5-11e7-8f53-802ca1c8de0d.png)

but may be it was an artifact from my work/testing on the update script.
may be it was only

**Comment by jcameron** [comment]
Thanks - I'll fix that in the next release. Fortunately it is harmless as that old code isn't used anywhere in Usermin.
