### ISSUE TITLE
Edit Categories: Failed to be saved

### ISSUE THREAD

**Issue by qooob** [webmin/usermin#23]
When in 

_Webmin/Usermin Configurations/Edit Categories_ try to set new name for category, for example _ other_ and hit _Save Categories_ you get this error:

`Failed to save categories : Missing description for usermin`

If you fill _usermin_, then something else come up.

**Comment by jcameron** [comment]
This works OK for me - are you editing the names of the default categories, or a custom category?

**Comment by qooob** [comment]
On the default, in Usermin configuration, on Fedora server.

**Comment by jcameron** [comment]
Ok, I see it now - a fix will be in the next webmin release.
