### ISSUE TITLE
LDAP details maintenance

### ISSUE THREAD

**Issue by viharm** [webmin/usermin#25]
I really like the usability of *Usermin*.

I have deployed a *Usermin* instance in my home network for users to be able to access their own account.

User account, details and authentication are managed via LDAP by an *OpenLDAP* instance.

Unfortunately I am unable to get the users to change their own password. When they try, they get the following error because the user details are not in the local `passwd` file.
```
Failed to change password : Your username was not found in the password file
```

Is there a solution for this?

**Comment by swelljoe** [comment]
Webmin->Usermin Configuration->Usermin Module Configuration->Change Password.

Set *Change with* to *Use PAM or passwd command*.

Assuming PAM or the passwd command are able to change passwords in LDAP with your current configuration, this should work.

**Comment by viharm** [comment]
It works, thanks.
