### ISSUE TITLE
MIME Type Programs

### ISSUE THREAD

**Issue by qooob** [webmin/usermin#3]
When going to MIME Type Programs module, clicking Preferences on top returns 404 error.

**Comment by jcameron** [comment]
Does this only happen with your theme, and/or only with that module?

**Comment by qooob** [comment]
It happens in all themes and only in this module. I had a second to debug it. It appears that the link for Preferences in MIME Type Programs module is `config.cgi`, while others have `uconfig.cgi` - changing it to `uconfig.cgi` works find. Just replace it and it will work as expected. It's a typo..

**Comment by jcameron** [comment]
Ok, I see the bug - this will be fixed in the next Usermin release.
