### ISSUE TITLE
Mail: Configurable message preview length

### ISSUE THREAD

**Issue by rostovtsev** [webmin/usermin#40]
Jamie,

Could you add an option for `mailbox/index.cgi` to accept an URL param for controlling preview length if enabled in options?

Besides, could you also add an option to Mailbox Configuration page, so user could define preview length?

To be clear, I need the first option because preview can be based on the screen width. In case user doesn't want it to work based on the width of the screen, he/she would be able to choose preferable preview length.

**Comment by jcameron** [comment]
Sure, I can do that. Do you also want previewing to be enabled via a URL parameter?

**Comment by qooob** [comment]
I don't think so. It's user defined. I could change it on the fly though, if needed.

Preview is somewhat different. It's programmatically defined, based on user's screen.

Thanks a lot, Jamie.
