### ISSUE TITLE
Mail folders: Inbox containing subfolders

### ISSUE THREAD

**Issue by rostovtsev** [webmin/usermin#42]
Hi, Jamie.

Anytime _IMAP_ is used and _Inbox_ folder has some subfolders, they are not correctly displayed (including on your folder-list select on Gray Theme) as _Inbox_ folder actually in _Maildir/_ root and subfolders are in _Maildir/.INBOX.Subfolder1_, _Maildir/.INBOX.Subfolder2_ and etc. Is there a way to make sure that _Inbox_ for IMAP is returned as actual folder name - _.INBOX_ and not - _Maildir_?

**Comment by jcameron** [comment]
Hmm .. can you attach a screenshot of what you're seeing there?

**Comment by rostovtsev** [comment]
Jamie, there, have a look.

![screenshot from 2018-07-16 22-35-13](https://user-images.githubusercontent.com/4426533/42779374-ea2cd746-8948-11e8-8189-477a75faa9bd.png)
![screenshot from 2018-07-16 22-35-20](https://user-images.githubusercontent.com/4426533/42779377-ea4a2468-8948-11e8-9626-665276f9364f.png)

It might look okay, but programmatically it's not. Inbox path is always returned as root folder, like `/home/user/Maildir`, while subfolders are `/home/user/Maildir/.INBOX.SubFolder1`. 

Do you think I should fix it locally? No problem then, I could do it.

**Comment by rostovtsev** [comment]
To remove `.INBOX` prefix from subfolders? If so, I don't think it's the right solution. What I did, to make the tree work properly, was on opposite, to treat `Mailbox/` as `Mailbox/.INBOX`.

**Comment by jcameron** [comment]
So is this a special thing that the IMAP server does? Do the actual mail directories have INBOX in the name?

**Comment by rostovtsev** [comment]
Subdirectories for Inbox, yes. They are starting from `.INBOX` but main Inbox is in `cur`. I think it's standard for IMAP. Nothing is wrong here.

In this case scenario, I think my initial issue, could be solved simply by placing subfolders of Inbox, right under Inbox, when sorted for select, however, I'm not sure anymore, what should be the best - sorry Jamie! It seems that everyone uses tricks, to combine subfolders of Inbox with actual Inbox to build a tree. This is what I did locally, and it works as designed.

I don't think there is an issue, as now I think it's just not possible to solve it using ordinary select.
