### ISSUE TITLE
Virtualmin GPL - NginX missing 

### ISSUE THREAD

**Issue by reers** [webmin/usermin#43]
Installing on fresh Centos 7.5
1. Install using ./install.sh -b LEMP
2. Restart NginX from webmin > servers > nginx
3. Error: sh: /etc/init.d/nginx: No such file or directory

Thank you.

**Comment by reers** [comment]
The internal code is Redhat Linux 15.5, and the system was installed yesterday.
The system was first updated, then installed using install.sh -b LEMP.

Thank you

**Comment by swelljoe** [comment]
I'm going to close this issue, as it isn't a Usermin issue (it's either a Webmin or virtualmin-nginx module issue, but I think it's Webmin that's misbehaving), and I've opened a new issue about it here in the Webmin tracker: https://github.com/webmin/webmin/issues/980
