### ISSUE TITLE
Errors in log when spam uconfig is missing

### ISSUE THREAD

**Issue by SpiffyStores** [webmin/usermin#44]
A clean install of Usermin does not create a uconfig file under the spam folder. This causes the following messages in the error log -

Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 669.
Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 670.
Use of uninitialized value $file in substitution (s///) at /usr/libexec/usermin/mailbox/mailbox-lib.pl line 672.

The problem can be solved by editing and saving a default user config for the spam module which creates an empty 'spam_file' entry, but maybe the code just check to see if the config entry is missing first.

**Comment by rostovtsev** [comment]
It's harmless warning. It will be added to the next Usermin release.

https://github.com/webmin/usermin/commit/10910ad8c39f62148be83c0e9cfa11fdaf8df655#diff-53be737db4eb01edc3723e763220905d
