### ISSUE TITLE
Shift Click to select multiple mails

### ISSUE THREAD

**Issue by gotjoshua** [webmin/usermin#45]
Feature request:
When shift clicking on a checkbox, i would love if the system selected all in the range between the current click and the previous click.

**Comment by jcameron** [comment]
@rostovtsev is this something the authentic theme could implement?

**Comment by gotjoshua** [comment]
Well, _really_ needed is probably a stretch, but it is a very nice to have feature, and a quite expected feature.

I think the right click thing is cute, but a context menu is expected (not an instant action).

I think that "clicking, holding and dragging (like desktop) " is totally UNnessesary.

Just storing the previously checked item in a variable and if shift key is down on the next click also select everything in between.

**Comment by rostovtsev** [comment]
It's added on the latest commit - give it a try! :nerd_face: 

Enjoy!

**Comment by gotjoshua** [comment]
Awesome! Brilliant :-)
Thanks for the quick response!
~
.:.joshua

“Our lives are not our own.
   We are bound to others, past and present,
     and by each crime and every kindness,
       we birth our future.”
           ― David Mitchell
<https://www.goodreads.com/author/show/6538289.David_Mitchell>, Cloud Atlas
<https://www.goodreads.com/work/quotes/1871423>

"Avoid the pursuit of happiness. Seek to define your mission and pursue
that."
   ― John Perry Barlow
<https://www.goodreads.com/author/show/273206.John_Perry_Barlow>

"Life is a series of gestures, into which we embed meaning..."
   ― *Joshua Gottdenker*

**Comment by rostovtsev** [comment]
Joshua, you are welcome to submit more suggestions! :smiley_cat: 

Thanks.
