### ISSUE TITLE
MariaDB Usermin (Debian 9)

### ISSUE THREAD

**Issue by shadowtor** [webmin/usermin#46]
![image](https://user-images.githubusercontent.com/4159051/53138284-ebb20a80-35d9-11e9-96bd-99f05a75e762.png)
Getting the above issue with recent updates on debian 9 (unable to add users to database when creating user or modifying)
![image](https://user-images.githubusercontent.com/4159051/53138335-17cd8b80-35da-11e9-85b0-b16c83b404a1.png)
Thanks! :)

**Comment by jcameron** [comment]
I just checked in code to fix this, which will be included in the next Webmin release.
