### ISSUE TITLE
Import MBOX file from Horde export

### ISSUE THREAD

**Issue by beppe9000** [webmin/usermin#48]
I have MBOX file but can't find a way to import like Horde ?

**Comment by rostovtsev** [comment]
Hi,

There are multiple ways of do it.

The simpliest way is just to upload existing _mbox_  file.

You could also use command line tools to download (by logging in to remote server) or convert from _mbox_  to _maildir_ . If you had _Virtualmin_  installed, you could use `virtualmin copy-mailbox` command.

**Comment by beppe9000** [comment]
> The simpliest way is just to upload existing mbox file.
Somehow I can't find the interface to do that... I think I looked everywhere.
If you could point me to that would be helpful indeed.

> If you had _Virtualmin_ installed, you could use `virtualmin copy-mailbox` command.
Do I need to run it as root or as the current user? Can I specify the email account where to import the mbox file: It's a backup of the inbox (select all emails and export from horde) of a info@me.tld email address whose domain I migrated to Virtualmin. I already created the users for the various email accounts so I just wanted to load the emails in it.

**Comment by rostovtsev** [comment]
Please have a look at this post:

https://www.virtualmin.com/node/9966

**Comment by beppe9000** [comment]
Thanks I'll give it a try. But what about the usermin method? Could you tell me the menu sequence to get to it ?

**Comment by rostovtsev** [comment]
At the moment, it's not possible. However, you could use File Manager under particular user to upload a file.

----

We will keep this in mind as possible feature to add in the future.

I will close this issue for now.

**Comment by beppe9000** [comment]
> At the moment, it's not possible. However, you could use File Manager under particular user to upload a file.

There is no way for a usermin user without shell access (non-root anyway) to import his own mbox file to the inbox?

**Comment by rostovtsev** [comment]
> Are you tracking these things elsewhere?

My personal notes only

> There is no way for a usermin user without shell access (non-root anyway) to import his own mbox file to the inbox?

You can not import (upload) your mbox (file) without shell access. _File Manager_  or _Upload and Download_  module can do the job for you. 

Users always have access to their files, by default, and can do whatever they need to do with it.

**Comment by jcameron** [comment]
We could add this as a feature though - it wouldn't be too hard.

**Comment by beppe9000** [comment]
> My personal notes only

That's rad ;)

> We could add this as a feature though - it wouldn't be too hard.

👍
