### ISSUE TITLE
In mailbox-lib.pl $body is defined but seemingly unused...

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#5]
In this line:

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L150

$body is defined, and possibly populated in the next conditional block, but seems to have nothing done with it. seems bug-like. Should this be an our variable? (I don't think I see it being used that way in other files, though, and other files have $body vars, and so there'd be a lot of ugliness there with masking the variable.)

Seems bug-like.

*Note:* This issue and several subsequent ones are linking into my fork of the usermin repo. I've completed (once these bugs are dealt with) doing a strict/warn conversion on the mailbox module, so llia and I can really start hacking away as an HTML5 version of the inbox. So, line numbers will not line up with your usermin repo. I'll grant you access to this one if you want to check in changes. Or, I can send a pull request and you can merge it into yours and fix it there. Or, you can tell me what to do, and I'll make the changes. I'm hesitant to make a pull request with something that is definitely currently broken (doesn't even compile). There's about a dozen breaking changes in this batch.

**Comment by jcameron** [comment]
I"m pretty sure that $body is useless - I've checked in a change to remove it.
