### ISSUE TITLE
GnuPG Encryption doesn't work

### ISSUE THREAD

**Issue by rostovtsev** [webmin/usermin#50]
When trying to setup new GPG private key, using _Usermin/Applications/GnuPG Encryption_ it just doesn't work. I tried bare metal machines and VMs (all possible distros).

In CentOS 7 however, you get output saying: `GnuPG has been successfully setup and a secret key generated`, but in reality no key is actually created. In Fedora, Debian, Ubuntu there is no output at all. It just hangs forever.

Right now, it's impossible to generate the key using UI.

Could you please take a look, Jamie?

**Comment by jcameron** [comment]
Thanks, I'll fix this in the next release.

**Comment by rostovtsev** [comment]
Thank you, Jamie, I will give it a try.

It might be possibly related - also, generating key in _Virtualmin/Backups_ didn't work for me when I last tried.

**Comment by rostovtsev** [comment]
There is only one issue - Key size is disrespected. No matter what you set 4096/8192 - it's always set to 2048.

..and in _Virtualmin/Backup and Restore/Create Encryption Key_ 

![image](https://user-images.githubusercontent.com/4426533/60003160-ca8a2500-9672-11e9-882a-77ecc407cfc9.png)



..also doesn't work and always fails with an error:

![image](https://user-images.githubusercontent.com/4426533/60003208-e42b6c80-9672-11e9-8ce0-10bcfed6faaf.png)


I just thought that it might be possibly related.

**Comment by rostovtsev** [comment]
Okay, `keysize` passed form element didn't exist. Fixed.
