### ISSUE TITLE
[usermin] fix for macOS PAM Service file /etc/pam.d/usermin 

### ISSUE THREAD

**Issue by gilcel** [webmin/usermin#57]
Hi usermin admins,

This is not an issue but more a fix ;-)

The "PAM service file" for Mac OS X / macOS in the usermin's "Install Requirements"  is (really) outdated here (see chapter: Under OSX....):
http://webmin.com/udownload.html

The fix works with usermin 1.791 and with newer macOS version and it should read:
```
# login: auth account password session
auth	  sufficient  pam_opendirectory.so try_first_pass
auth	  required    pam_deny.so
account	 required     pam_permit.so
password required    pam_deny.so
session	required      pam_permit.so
```

Using `pam_securityserver.so` is really outdated (back to 10.4 I think).

Hope this helps someone,

gilles

**Comment by jcameron** [comment]
thanks, we'll update the docs with this config.
