### ISSUE TITLE
Some mails are blank, but visible in "raw"

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#58]
Some kinds of HTML email don't show up at all in the Read Mail module, though the contents can be seen with "View raw message".

An example email that exhibits this behavior: http://calport.com/open/email.txt

I don't see any clues, but I don't have any insight into the mail parser.

**Comment by jcameron** [comment]
Looks like a bug in parsing the message content. Could you forward one of these to me as an attachment, including all the headers?

**Comment by swelljoe** [comment]
The one I linked above is the only one I have (though maybe I can find one in my own mailbox, since it has been reported by multiple people).

**Comment by swelljoe** [comment]
I found another example in my own mailbox, and sent it to you.

**Comment by jcameron** [comment]
Looks like that example email has only HTML contents, but no text. There's an option on the preferences page that controls if the body can be shown as HTML or not .. the default is only text, which could cause this to show up as blank (at least, it did in my tests just now).

**Comment by swelljoe** [comment]
So...to end users that just looks like it doesn't work. I don't know what the right thing is, but this definitely aint it! ;-)

**Comment by swelljoe** [comment]
Are we concerned about dangerous content, or is there some other reason to not show HTML by default?

**Comment by swelljoe** [comment]
Is it safe to change the default on this to allow HTML? I guess we don't have mechanisms for blocking media until permitted (as Thunderbird does), so maybe tracking images are an issue...but, probably less of a problem than "email is blank".

**Comment by iliarostovtsev** [comment]
> Is it safe to change the default on this to allow HTML?

It should be considerably safe.

> I guess we don't have mechanisms for blocking media until permitted (as Thunderbird does),

We do.

![image](https://user-images.githubusercontent.com/4426533/85920343-7dd7bc00-b87b-11ea-8aa7-c79a7830787d.png)


> .. so maybe tracking images are an issue...but, probably less of a problem than "email is blank".

Certainly.

https://github.com/webmin/usermin/commit/2a3a1cd64cd8003db115990811e2df8faa76b767
https://github.com/virtualmin/Virtualmin-Config/commit/2af57a5a1edcf54723c3f40f7565659a91d79fe7

**Comment by jcameron** [comment]
I do think it's safe to allow HTML by default - I'll make that switch in the next Usermin release.

**Comment by iliarostovtsev** [comment]
Haven't I already done it in the commits above?

**Comment by jcameron** [comment]
Your commit https://github.com/webmin/usermin/commit/2a3a1cd64cd8003db115990811e2df8faa76b767 is in the wrong files.

**Comment by iliarostovtsev** [comment]
Oh, sorry, I thought I did it https://github.com/webmin/usermin/blob/2a3a1cd64cd8003db115990811e2df8faa76b767/mailbox/defaultuconfig.
