### ISSUE TITLE
In mailbox-lib.pl $file is undefined in two places

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#6]
In this line:

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1054

And in:

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1063

$file is undefined. I'm not sure if it's trying to delete the folder it's in once empty, or if that should be $ifile, or something else.

**Comment by jcameron** [comment]
Thanks, I've checked in a fix
