### ISSUE TITLE
Encoding issue #3

### ISSUE THREAD

**Issue by DrCarsonBeckett** [webmin/usermin#66]
Oh, I see.. try the following .. open `/etc/dovecot/conf.d/10-mail.conf` and tweak default mail location value from:

~~~
mail_location = maildir:~/Maildir
~~~

.. to:

~~~
mail_location = maildir:~/Maildir/:UTF-8
~~~

.. and restart Dovecot:

~~~
systemctl restart dovecot
~~~

_Originally posted by @iliarostovtsev in https://github.com/webmin/usermin/issues/65#issuecomment-731652862_

I don't really like that issues getting closed without waiting for verification.
It did not solve the issue.
The thing is, the folder name gets displayed correctly if you check in Usermin with the function "Manage Folders", but if you then take a look at the folders in the Mail tab then you will see it gets displayed wrong:
> TEst-ÃÃÃ-Ã¶Ã¤Ã¼

Displayed correctly in "Manage Folders":

> TEst-ÖÄÜ-öäü | /home/xxx/homes/xxx/Maildir/.TEst-ÖÄÜ-öäü

And I did apply the patch @iliarostovtsev mentioned and of course I did restart dovecot and usermin too (just to be sure).

System:
Debian 10
Webmin-Version | 1.962
Usermin-Version | 1.812
Virtualmin Version | 6.14
Authentic theme version | 19.62

**Comment by iliarostovtsev** [comment]
Hi,

> I don't really like that issues getting closed without waiting for verification.

Sorry, I really thought it just works. It does for me.

If you set mail location to use _utf-8_ the folders will be created using native charset (without escaping).

Note, that mail location can be used either with default _utf-7_ or set to use _utf-8_ (not both at the same time).

Is there still an issue for you?

If you connect using Thunderbird using new Dovecot mail location _utf-8_ option, does it create mail folder without using escaping?

**Comment by DrCarsonBeckett** [comment]
No problem.
I just created a new folder and it does use native charset instead of encoded ones.
It gets displayed corrrectly in the managed folders tab, but again not in the mail tab.

**Comment by iliarostovtsev** [comment]
Have you tired some other browser or/and different PC?

It does display correctly for me? Can you provide a screenshot for both left menu and `ls -lsa` output for `~/Maildir`?

**Comment by DrCarsonBeckett** [comment]
Its the same problem on IE, Edge, Firefox and also on iOS Firefox and Safari. I tested it on another PC as well (Firefox) and its the same problem.
![2020-11-22_15h40_03](https://user-images.githubusercontent.com/38506927/99906929-1747b480-2cda-11eb-93de-0fde84647f22.png)
![2020-11-22_15h39_54](https://user-images.githubusercontent.com/38506927/99906931-17e04b00-2cda-11eb-9722-47d72b34a0b5.png)
![2020-11-22_15h39_39](https://user-images.githubusercontent.com/38506927/99906932-17e04b00-2cda-11eb-9310-32b9a4bbf11e.png)

**Comment by iliarostovtsev** [comment]
What happens if you create a folder containing special character using Thunderbird?

**Comment by DrCarsonBeckett** [comment]
I don't use Thunderbird, but one folder of the Test folders with öäü is created from Outlook and the other one directly in Usermin.

**Comment by iliarostovtsev** [comment]
.. and in neither way it's displayed correctly?

.. wouldn't it be hard to try the latest Thunderbird to make sure we're on the same page?

**Comment by DrCarsonBeckett** [comment]
Just tested it in Thunderbird (latest version).
It gets displayed correctly, meaning the same as in Outlook and iOS Mail app.
Only issue is that its not displayed correctly in Usermin.

**Comment by iliarostovtsev** [comment]
> I just wanted to report that issue, because I think that great software should have as less issues as possible.

Thanks! I think, I know why this issue is happening on your side - you have **Mail storage format for Inbox** set to **Maildir** in **Webmin > Usermin > Usermin Module Configuration > Read Mail**. When I was testing it, I had it set to IMAP.

Now it makes sense. I will have a look in fixing it.

**Comment by iliarostovtsev** [comment]
Okay, I found the reason why it's failing. I will push a patch when finish re-working my build system.

**Comment by DrCarsonBeckett** [comment]
Sounds good, no pressure. Ones its finished, I will gladly test it.

**Comment by iliarostovtsev** [comment]
Okay, give it a try with the latest theme patches! It should fix an issue with folders!
