### ISSUE TITLE
Wrong encoding in browser interface

### ISSUE THREAD

**Issue by HonkXL** [webmin/usermin#68]
Browser interface uses wrong encoding for special characters like German Umlauts.
The problem is visible in the folder of the mails (like Entwürfe) and in the subjects of mails.

See screenshot.

It's independent of the used webbrowser. Usermin is 1.812, Authentic theme 19.62

![usermin](https://user-images.githubusercontent.com/16715040/109619526-2c35ae80-7b39-11eb-9388-1be4fae31a6a.jpg)

**Comment by iliarostovtsev** [comment]
Hi,

At the moment the latest Usermin version is 1.820 and it addresses the issues you're reporting. [Give it a try](https://download.webmin.com/download/).

**Comment by HonkXL** [comment]
Upgrading would be a good idea, but I use it on a VirtualMin installation and here the 1.812 is the latest version in the repo:
http://software.virtualmin.com/vm/6/gpl/universal/

Or is it better to adress this at VirtualMin?

**Comment by iliarostovtsev** [comment]
You're right. We'll update it, thanks!

Meanwhile, you can easily install it by downloading it from [Usermin page](http://usermin.com/usermin.html).

**Comment by HonkXL** [comment]
I posted this to the Virtualmin forum. The repo was not updated due to a bug in Webmin that seems to make it incompatible with Virtualmin!?

Here the forum post:

https://forum.virtualmin.com/t/old-webmin-virtualmin-in-the-repo-of-virtualmin/109624/3

**Comment by HonkXL** [comment]
I updated Webmin to 1.823 - now it's partially fixed.
The folder names on the left side are ok.
In the subject, sometimes it's ok and for other mails not. See screenshot. I marked it in red (not ok) and green (ok).

![usermin](https://user-images.githubusercontent.com/16715040/110917556-54cc5e00-831a-11eb-8bb7-091b68e3d75b.png)

**Comment by HonkXL** [comment]
The difference is:

It's not working when the subject is coded in ISO-8859:
Subject: =?ISO-8859-1?Q?Gute_Unterhaltung_f=FCr_zu_Hause?=

But it's working when UTF8:
Subject: OFB =?utf-8?Q?H=C3=B6gy=C3=A9sz=3A?= Anstehende Ereignisse

Both lines are from the mails shown above.

**Comment by iliarostovtsev** [comment]
If you try opening the same email using **Webmin ⇾ Servers ⇾ Read User Mail** module how is it getting displayed?

**Comment by HonkXL** [comment]
Here it is ok:

![webmin-read-user-mail](https://user-images.githubusercontent.com/16715040/110951498-6c6d0c00-8345-11eb-9332-b76e68105c42.png)

**Comment by iliarostovtsev** [comment]
Looks correct. Could you download email me those three emails?
(my email can be found in [comments](https://github.com/authentic-theme/authentic-theme/blob/master/authentic-funcs.pl))

**Comment by iliarostovtsev** [comment]
Looks correct. Could you download email me those three emails?
(my email can be found in [comments](https://github.com/authentic-theme/authentic-theme/blob/master/authentic-funcs.pl))

**Comment by HonkXL** [comment]
Since the last update I can no longer reproduce this - I think it's fixed.
