### ISSUE TITLE
Dark Mode for login page not supported (as is for webmin)

### ISSUE THREAD

**Issue by by** [webmin/usermin#71]
Contrary to webmin, usermin w/ Authentic Theme does not support Dark Mode in "Login page color palette" and also does not support "Show branding splash screen on initial loading".

It would be great, if you could extend this to usermin as well, thank you!

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up!

Do you mean branding cannot be disabled for Usermin?

Do you mean when you change to have dark mode on theme configuration in Webmin it doesn't affect Usermin?

Thinking of this now, it looks very likely. If so, I will fix it with upcoming 19.74 theme release.

**Comment by iliarostovtsev** [comment]
Fixed.
