### ISSUE TITLE
“virtual server > edit users > (user) > login to usermin”. redirects to localhost:20000

### ISSUE THREAD

**Issue by jucajuca** [webmin/usermin#73]
I have webmin and usermin running behind an apache proxy. Both work normally if I just access them directly (e.g. webmin.domain.tdl; usermin.domain.tld). This means that the apache server is properly configured.

However when I go to "virtual server > edit users > (user) > login to usermin" the redirect is still nor working properly. It will open a new window and redirect it to localhost:20000

This happens in 3 different servers.

Related to this issue:

https://github.com/webmin/usermin/issues/64

Info about the system

SYSTEM INFORMATION|
Operating system Debian Linux 10
Webmin version 1.981 Usermin version 1.823
Virtualmin version 6.17-3 Authentic theme version 19.83-2

Time on system Thursday, November 4, 2021 11:39 AM
Kernel and CPU Linux 4.19.0-17-amd64 on x86_64
Processor information AMD EPYC 7702P 64-Core Processor, 4 cores System uptime 10 days, 17 hours, 05 minutes

**Comment by jcameron** [comment]
Thanks for reporting this - I see the bug, and it will be fixed in the next Webmin release.

**Comment by jucajuca** [comment]
Unfortunately the error is still happening, can you have a look? The only difference that I noted is that the user session of the originating window will be closed.

It still redirects to localhost:20000

![image](https://user-images.githubusercontent.com/67229094/173635091-7d06cee8-bdef-479d-8955-9cfa27fb0709.png)

**Comment by iliajie** [comment]
@jucajuca Juan, check this out https://github.com/webmin/webmin/pull/1588#issuecomment-1082343166.
