### ISSUE TITLE
Changing password issue

### ISSUE THREAD

**Issue by iliajie** [webmin/usermin#78]
When changing a password using Usermin (latest dev builds) it doesn't work and the following error is thrown:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4426533/174824201-a19b3407-a473-449f-95f3-7f742da4e709.png">

Although, the file exists:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4426533/174824476-1383c6c9-95e5-4fc6-9c8e-825db52f1fa8.png">

**Comment by jcameron** [comment]
What's the first line of that file?

**Comment by iliajie** [comment]
Duh, you're right! I synced it from repos but forgot to symlink`/usr/bin/perl` to `/usr/local/bin/perl`.
