### ISSUE TITLE
In mailbox-lib.pl @mail is undefined in several places

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#8]
In these lines:

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1738

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1751

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1759

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1765

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1771

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L1784

I don't see how @mail is getting populated. I feel silly for this one, but I can't wrap my head around where it's supposed to come from. It's called with $mail, but I don't see how that could become @mail, so that's not it. I see mail get defined on 1415 in another subroutine, but that's in another scope (or, at least, it is now and I don't think that'd be called under all circumstances, so can't be relied on).

Maybe it's a folders-lib.pl thing?

**Comment by jcameron** [comment]
The code should be using $mail , but happens to work due to scoping. Fixed with https://github.com/webmin/usermin/commit/e43119ea54678891c9114f23c289312b07cb492b
