### ISSUE TITLE
Mailbox Folder message list view Subject Encoding bug.

### ISSUE THREAD

**Issue by chris001** [webmin/usermin#80]
When you view the Folder message list, **for some message subjects** containing an emoji, the character encoding processing fails, and it displays: accented s characters, copyright symbol, greek language looking character, etc.
Example:   ðŸ“¦ ORDER DELIVERED: ....

However, in the `view_mail.cgi` message view, the encoding is correct, it displays the emoji.
Example: 📦 ORDER DELIVERED: ....

Note, sometimes, the emoji shows correctly in both views - Folder message list, and View mail message.
Example:  ✅ ORDER CONFIRMED: ....

**Comment by jcameron** [comment]
If you view the raw email headers, what does the `Subject:` line contain for one of these emails that's not shown correctly?

**Comment by chris001** [comment]
Mailbox folder message list view, the emoji encode bug, right click Inspect:
`<span class="mail-list-mrow mail-list-mrow-subject">ðŸšš ORDER UPDATE: For OnePlus Nord N20...</span>`

View raw message (From the `view_mail.cgi` which encodes the emoji correctly):
`Subject: =?UTF-8?Q?=F0=9F=9A=9A_ORDER_UPDATE:_For_OnePlus_Nord_N20...?=`

**Comment by jcameron** [comment]
Would it be possible for you to send me an email like this at jcameron@virtualmin.com ?

**Comment by jcameron** [comment]
Actually, no worries .. I was able to reproduce this. It only happens with the newer Authentic Theme though .. 

@iliajie could you take a look at this?

**Comment by iliajie** [comment]
Hello, Chris. Congratulations on the new phone! 🙂 

Look, I have tried your subject string and it worked for me:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/4426533/177633396-304b4d6f-080e-4201-8f77-0d2b9388eb3c.png">

Can you share that email message with me so I could reproduce the issue? Try getting my email in comments in headers of Authentic.

**Comment by chris001** [comment]
Thanks!  Forwarded a failing emoji email to you!

**Comment by iliajie** [comment]
Thanks Chris. Can you please not forward it but send it to me as a file attachment?

**Comment by chris001** [comment]
When it fails, it displays one ASCII character for each of the 4 hex bytes of the UTF-8 string (`F0 9F 9A 9A`).
When it works, it takes the 4 hex bytes together, and displays the corresponding emoji.

**Comment by chris001** [comment]
Sent as attachment!

**Comment by iliajie** [comment]
> You're on Mac with Safari?

I'm on Mac but with Chrome and Firefox. Safari is a troubled child.

I really cannot repro this, as it displays perfectly fine in mail listing and when viewing mail. Do you have any specific encodings selected/used?

I always have it loaded as this, no matter what:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/4426533/177890013-765b5e3a-79bf-4db7-b2a1-724d04f21a93.png">

**Comment by chris001** [comment]
On the client OS, settings are default to English US.
On the Virtualmin server:
```
chris:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
chris:~$
```

**Comment by chris001** [comment]
Same emoji failure on MS Edge browser (uses same engine as Chrome for html page rendering).

How is the code different for displaying the Subject for the list view of 20 messages in the mailbox, versus `view_mail.cgi` which display Subject, other headers, and message body?

**Comment by chris001** [comment]
> Actually, no worries .. I was able to reproduce this. It only happens with the newer Authentic Theme though ..

@jcameron Could you share your steps to reproduce, OS, browser, add-ons, etc., so @iliajie could reproduce.

@iliajie I sent the message to a free web mail account (protonmail) and it displayed the emoji in the Subject correctly in both mailbox messages list view, and full message view.  

Also, when access Usermin from a different computer, with Edge browser (chromium engine), same bug, Subject emoji in mailbox messages list view is fail.  Charset on both Usermin pages (list view and message view) is `Unicode (UTF-8)` verified by the Chrome extension "[Encoding](https://microsoftedge.microsoft.com/addons/detail/charset/ljameaionljangkhnobkellagnjjohno)".

So this bug has to be located on the Usermin side, reproduced by both Jamie and me.

**Comment by iliajie** [comment]
> Charset on both Usermin pages (list view and message view) is Unicode (UTF-8) verified by the Chrome extension "[Encoding](https://microsoftedge.microsoft.com/addons/detail/charset/ljameaionljangkhnobkellagnjjohno)".

What if you try in incognito tab or with all extensions disabled -- does it change anyhting?

**Comment by chris001** [comment]
FF "private window" = fail to display emoji.
FF "Troubleshoot mode (restart with all add-ons disabled)" = fail to display emoji.
However, one emoji display correctly in a mailbox message list view Subject, this one: "✅ ORDER CONFIRMED ...".   Why?  The answer should narrow down the cause of this bug.

**Comment by iliajie** [comment]
Can I see your `/etc/usermin/mailbox/config` and also probably `/etc/webmin/mailboxes/config` files? I tried everything (without looking at the code) .. and it works.

I am not sure why there is a green tick when it supposed to be a truck?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4426533/178067707-5c8ecc88-1c67-4a27-9f8c-1e9ba16f0d10.png">

By the way what is your mail system set to? Is it IMAP mode or reading Maildir directly?

**Comment by chris001** [comment]
The green tick is supposed to display as a green tick.  It's a totally different notification email, intended to communicate, "your order is confirmed, payment transaction completed on your side, now expect the next notification email".
```
cat /etc/usermin/mailbox/config
no_crlf=0
mail_dir=/var/spool/mail
no_orig_ip=1
mail_style=0
pop3_ssl=0
folder_types=local,ext,pop3,imap
sendmail_path=/usr/lib/sendmail
spam_report=
perpage=20
mail_system=0
top_buttons=1
show_to=0
no_mailer=0
wrap_width=80
server_attach=0
smtp_ssl=0
pop_locks=1
from_format=1
noindex_hostname=0
view_images=1
mail_file=mbox
nologout=0
folder_virts=virt,comp
edit_from=1
view_html=2
spam_always=0
html_base64=0
shortindex=0
mail_dir_qmail=Maildir
from_map=/etc/mail/virtusertable
```

```
sudo cat /etc/webmin/mailboxes/config
from_virtualmin=1
ignore_users_enabled=0
show_to=0
fwd_mode=0
sync_modify=1
no_orig_ip=0
spam_report=
date_fmt=dmy
maildir_deleted=0
max_records=200
mail_dir=Maildir
wrap_width=80
perpage=20
mailbox_user=.usermin/mailbox
show_unread=0
mail_system=0
show_size_below=0
no_crlf=0
column_count=4
arrows=1
mail_file=Mailbox
noindex_hostname=0
sync_delete=1
show_size=1
open_mode=0
sig_file=*
log_read=0
show_body=0
link_mode=0
track_read=0
html_edit=0
show_count=0
size_mode=1
check_mod=1
sync_perms=0700
top_buttons=2
auto=1
mail_style=0
html_quote=0
vpopmail_dir=/home/vpopmail
view_html=0
spam_del=0
spam_buttons=mail
no_mailer=0
ignore_users=
show_mail=0
mail_usermin=mail
delete_warn=y
show_sent=0
show_delall=0
sync_create=0
sort_mode=1
```
IMAP or Maildir?  Not sure.  No change from default.

**Comment by iliajie** [comment]
It appears you're using `mbox`. This cannot be default?

Can I see a screenshot of what you're seeing in UI?

@jcameron Jamie, did you also repro this issue with `mbox` mail system?

**Comment by chris001** [comment]
I didn't change mail system storage type.  Usermin doesn't notify about `mbox` storage type.  Should it show an error or warning?  Should mail storage be converted to `Maildir`?  Command line or UI setting?
Screenshot of emoji fail:
![usermin emoji display bug](https://user-images.githubusercontent.com/259416/178079018-5f307b05-d4da-4cc0-994a-32fa96397524.png)

**Comment by jcameron** [comment]
No, I was able to reproduce this on a system using Maildir. For sure this isn't related to the mailbox format..

**Comment by chris001** [comment]
@jcameron  Client OS?  Broswer?  Steps to reproduce?
@iliajie Does `Usermin` or `miniserv` output an error or warning log line if/when they catch an error while they attempt and fail to render email headers with `UTF-8` emoji to HTML for the user?

**Comment by jcameron** [comment]
I see this using Chrome on MacOS, by just sending an email from gmail to myself with that "order update" emoji copy-pasted into the subject.

**Comment by chris001** [comment]
About converting `mbox` to `Maildir`, comment whether the following be the accurate conversion method:
1. When `procmail` is used by `postfix` to deliver locally:
`sudo nano /etc/procmailrc` 
Add a line:
`DEFAULT=$HOME/Maildir/`

2. `sudo systemctl restart postfix`

3. For new users to have `Maildir/` after creation do:
```
sudo mkdir -p /etc/skel/Maildir/new
sudo mkdir -p /etc/skel/Maildir/cur
sudo mkdir -p /etc/skel/Maildir/tmp
```

**Comment by chris001** [comment]
This looks interesting, where it does the [encode Subject](https://github.com/webmin/authentic-theme/blob/7f76744994bba27fc978ca8421e4e972aba1c71b/extensions/mail/mail-lib.pl#L571)

**Comment by chris001** [comment]
OK, together we found the cause of this Subject emoji display bug!

[Brilliant feature to safely edit files in `UTF-8` charset without failing to display them properly by auto detect their `charset`](https://github.com/webmin/webmin/pull/543).

[Possibly missed checking in a fix to detect when the required perl library not installed, and install it and warn admin if fail](https://github.com/webmin/webmin/pull/543#issuecomment-299090853).

**Comment by iliajie** [comment]
Thank you for reporting this, Chris!
