### ISSUE TITLE
Refresh button at top of Mailbox Message List doesn't work.

### ISSUE THREAD

**Issue by chris001** [webmin/usermin#84]
You have to hit the Browser button "Refresh page" to make it show the new mail.
Browsers: FF on W10, Edge (Chrome engine) on W10.

**Comment by jcameron** [comment]
@iliajie possible theme issue?

**Comment by chris001** [comment]
NB The Refresh button at the top right of the Dashboard page actually does work.  Why?

**Comment by iliajie** [comment]
> @iliajie possible theme issue?

🤷🏻‍♂️ 

> You have to hit the Browser button "Refresh page" to make it show the new mail.

It works for me:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4426533/179037670-ebd4035a-755f-413c-ad05-f9979eb40522.png">

Doesn't it work for you?

**Comment by chris001** [comment]
Correct!  That "Refresh" button in Usermin (in your screenshot above) doesn't work here, in Firefox or Edge (chrome engine) on W10.  Note, **this Refresh button used to work, many versions ago**, same browsers (also many versions ago!), however, no longer, in fact, it hasn't worked for quite some time - 6-12 months?

**Comment by chris001** [comment]
The browser console (on both FF and Edge/chrome) has: Deprecation warnings (about "Moment.js" , "zoom", "InstallTrigger" ), and some Uncaught js errors.

Screenshot from Edge/chrome:
![usermin refresh fail 1](https://user-images.githubusercontent.com/259416/179286281-c394a588-dc06-4ccd-ad4a-2a1d4e4f7786.png)


Expand tab "Tracking Prevention blocked access to storage":
![usermin refresh fail 2](https://user-images.githubusercontent.com/259416/179283596-feeee4e0-b6c4-4847-a48b-832646c4d276.png)

One JS Error is "Uncaught TypeError: data.list is undefined", when you click on "Trash" mailbox, which causes Usermin to throw error, and you continue to see the previous mailbox's message list view.

Other empty mailboxes (e.g. "drafts" in lower case, not to be confused with "Drafts", which contains many draft messges), show the icon "NO MAIL" at top of the message list view.  

FYI Usermin moves any deleted mails to the "Deleted Messages" mailbox, not to the "Trash" mailbox.

**Comment by iliajie** [comment]
Interesting! 🙂 What happens if you fully reload the page?

Based on error messages I don't see how this is a theme issue. What is `net::ERR_NAME_NOT_RESOLVED` error? I don't get it on my side.

**Comment by chris001** [comment]
Fully reload page (browser button) will reload all page contents, mailbox message list, and show new messages, if any.  Will try to reproduce `net::ERR_NAME_NOT_RESOLVED` error...

**Comment by chris001** [comment]
The Usermin Refresh icon doesn't spin, because it's fail.  However, Dashboard Refresh icon spins, because it works!

**Comment by Stephano2000** [comment]
The mailbox message list refresh button works here, though instead of it spinning, the mail folder in the left panel is highlighted with an animated background.

**Comment by iliajie** [comment]
This issue will be fixed on the next Usermin release.
