### ISSUE TITLE
Usermin fails to start after updating to 1.860

### ISSUE THREAD

**Issue by g7rau** [webmin/usermin#86]
Hi

Just a note, I upgraded to 1.860 from the usermin config area in webmin 2.000. It downloaded fine and seemed to install ok then errored 
data-fatal-error-text
Script was not run with full path (failed to find /usr/local/usermin-1.860/updateboot.pl under /usr/share/webmin

I tried reinstalling from the config area in webmin but no joy and no errors after. I checked in /usr/share/webmin and updateboot.pl wasnt there. I reran the set up from /usr/local/usermin-1.860/ and was able to manually start usermin. After I copied updateboot.pl to /usr/share/webmin it now works as expected within webmin.

My OS is old, Debian 9 on the extended support as I am so paranoid of another major upgrade on the server so maybe this might be a part of it. 

Anyway, thought you would want to know about the failure. 

Webmin / Usermin is still the best server managment tool for Linux in my eyes, I used it from the early days and cant imagine a server without it.  

Cheers Dave

**Comment by jcameron** [comment]
How did you install Usermin initially? Was it from a Debian package, or the tar.gz file?

**Comment by g7rau** [comment]
Hi Jamie. 

  

from the deb download on your site, not via the os. 

  

cheers, Dave 

  

Jamie Cameron ***@***.***> wrote ..  

  How did you install Usermin initially? Was it from a Debian package, or the tar.gz file? 

� Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>  

 .......................... Dave Edwards (G7RAU) email: ***@***.*** Web: http://www.g7rau.co.uk/ ..........................

**Comment by g7rau** [comment]
Hi Jamie. 

  

from the deb download on your site, not via the os. 

  

cheers, Dave 

  

Jamie Cameron ***@***.***> wrote ..  

  How did you install Usermin initially? Was it from a Debian package, or the tar.gz file? 

� Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>  

 .......................... Dave Edwards (G7RAU) email: ***@***.*** Web: http://www.g7rau.co.uk/ ..........................   

 .......................... Dave Edwards (G7RAU) email: ***@***.*** Web: http://www.g7rau.co.uk/ ..........................

**Comment by iliajie** [comment]
Usermin 1.860 works just fine for me on Debian 9.

I think you could remove Usermin completely (probably preserving `/etc/usermin` directory), and then reinstall it from [Usermin](https://github.com/webmin/usermin/releases/tag/1.860) release page.

Before reinstalling Usermin, kill all found Usermin PIDs by running `ps aux | grep usermin/miniserv.pl` command.

**Comment by g7rau** [comment]
Hi Ilia

Already done and fixed, this is only a note in case this was something more than a legacy issue  and others encountered this. I will close it now. Hoping to update Debian this winter, even my intranet page still says "using Deb 3.1 on..." heehee.

Regards

Dave
