### ISSUE TITLE
[feature] roundcube support?

### ISSUE THREAD

**Issue by u007** [webmin/usermin#87]
hi anyway to allow user to switch to roundcube from within usermin?
without needing to install script

**Comment by swelljoe** [comment]
No. Usermin is not a full-featured web server or PHP app server that can host Roundcube (which is written in PHP). Usermin runs in miniserv.pl, which is a Perl app server.

It is, however, entirely possible to just install Roundcube one time in one of your domains and allow all users for all domains to access it.
