### ISSUE TITLE
In mailbox-lib.pl $qid and $subs are undefined

### ISSUE THREAD

**Issue by swelljoe** [webmin/usermin#9]
In these lines:

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L2217

https://github.com/swelljoe/usermin/blob/master/mailbox/mailbox-lib.pl#L2218

$qid and $subs are undefined, as far as I can tell.

**Comment by jcameron** [comment]
Looks like the code assumes they are visible from the calling scope. I'll check in a fix for that.
