### ISSUE TITLE
Return to mailbox button goes under certain circumstances to page 1 instead of the current page

### ISSUE THREAD

**Issue by Stephano2000** [webmin/usermin#94]
Steps to reproduce:
- Logon to Usermin
- Click on the spam folder (bug might be present for other folders too)
- Click next page
- Click on any email
- Click Return to mailbox button. It will return as expected to page 2
- Click on any email
- Click Report as spam
- Click Return to mailbox button. It will return to page 1

There are some other operations as well that lead to Return to mailbox loosing the "start=" value.

Also shouldn't there be a page selector that leads directly to the requested page?

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix this in the next Usermin release.

**Comment by Stephano2000** [comment]
Great!

What about having a page selector to go directly to the desired page?

**Comment by iliajie** [comment]
Thanks for the heads up! The original issue has been fixed.

> What about having a page selector to go directly to the desired page?

If you have a new suggestion or found a new bug, please be kind to open a separate ticket.
