### ISSUE TITLE
HTML emails get Usermin styling.

### ISSUE THREAD

**Issue by MarcHagen** [webmin/usermin#99]
The current Usermin styling makes it hard to read emails as they also get the same style applied.
I cannot image this is a feature.

![image](https://user-images.githubusercontent.com/980978/236647042-01b84fb1-f2ba-4d25-8196-9395c1737998.png)

Please make a email content container without ANY (or minimal) basis HTML styling to improve email reading,

**Comment by jcameron** [comment]
Yeah, this is something we're working on - we need to move HTML emails into an iframe so they have their own styling.

**Comment by iliajie** [comment]
I will look into adding it ..
